### ISSUE TITLE
Add Companion Relationships table.

### ISSUE THREAD

**Issue by kelle** [SIMPLE-AstroDB/SIMPLE-db#230] opened 2021-12-15 19:14 UTC
When there are multiple objects in a system, it can get messy.  I propose that we have a separate source for each resolved object. E.g., Luhman 16AB would be three sources. 
- Luhman 16AB - the unresolved system
- Luhman 16A - the resolved primary
- Luhman 16B - the resolved secondary

If we do that, do we also want to add a column -- or a new table? -- which somehow connects the sources to each other? 

We could follow the SIMBAD model of using parent, children, and siblings. We could make a new dedicated table (Systems?), or add three columns to the Sources table for parent, children, and siblings.

**Comment by dr-rodriguez** [comment] 2021-12-21 21:57
Two possibilities we talked about:

1. Parent-Child model
We explicitly create both parent and child Sources and the parent Source contains a table 'member' that list parent and child. Multiple children would be multiple rows with the same parent. 'Siblings' would have the same parent but still require that a parent exist.

2. Graph database model
This is a standard approach to storing relationships (sometimes called 'edges') between entities (sometimes called 'nodes'). A member table would exist with entity1, entity2, relationship type. There would be relationships like parent-child and sibling. This allows us to link together two sources without having a parent and to also create parent-child relationships as needed. Here's some intro example for a GraphDB (neo4j): https://neo4j.com/developer/graph-database/  I don't recommend we switch DB architecture, but rather look at how they model it and approximate it with our setup.

Both setups will require some investigation and thinking about how to best implement them.

**Comment by kelle** [comment] 2022-01-18 20:41
Simbad's Parent-Child model: https://simbad.u-strasbg.fr/Pages/data_hierarchy.htx

**Comment by kelle** [comment] 2022-04-19 20:15
After discussion, I like the idea of adding a Relationships table with at least three columns: source1, source2, relationship of source 2 to source 1. Source1 and source2 should be in the Sources table.

If we wanted to add relationships to things not included in the Sources table (for example, G star primary or Tuc-Hor moving group), we could explore using the Virtual Parent option used by Simbad.

**Comment by kelle** [comment] 2023-04-28 22:19
We should check out Emily Calamari's (@ecalamari) sample as a use case to help develop this idea. (#370).

**Comment by ecalamari** [comment] 2023-05-03 15:10
Attaching my compiled list of UCDs that are in mostly binary, but some multiple, systems. These are all L or T dwarfs confirmed to be co-moving with FG or K type primary stars. The references column refers to another list which I have not included here but if that is relevant I can update that column accordingly. The only unpublished sources -- that are soon to be published -- are those with Ref column "Austin" entry.

[LTY+FGK_Companions.csv](https://github.com/SIMPLE-AstroDB/SIMPLE-db/files/11383942/LTY%2BFGK_Companions.csv)

**Comment by kelle** [comment] 2023-05-10 21:14
Thinking about Emily's sample more has made me realize we have two different scenarios:
- multiple systems where all the components are also sources. Eg, multiple brown dwarf systems.
- multiple systems where there's a higher mass component that has parameters we might want to adopt for the Source.  I'm going to start a new issue for this "benchmark" scenario.

**Comment by kelle** [comment] 2023-05-16 19:55
Unresolved AB source will be a `unresolved parent` to resolved A and B sources.

**Comment by SherelynA** [comment] 2023-09-13 18:17
Since the companion relationships table is merged, this issue should be closed. However, I noticed there were no references for most of the sources in the companion relationships table. We should make sure to add them!

**Comment by dr-rodriguez** [comment] 2023-09-13 18:18
Worked in #385

**Comment by dr-rodriguez** [comment] 2023-09-13 18:32
BTW, we may also want to create a release with this so that the website starts showing this table.

**Closed** 2024-01-02 19:10 UTC
Labels: database schema, template schema
